# -*- coding: utf-8 -*-
"""Task 2: Calculator from my Python learning series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XqFsmZKwpOfxsleKteg-ENu2uXYGI8dW
"""

def calculator():
    num1 = float(input("Enter first number: "))
    operator = input("Enter operation (+, -, *, /): ")
    num2 = float(input("Enter second number: "))

    if operator == '+':
        result = num1 + num2
    elif operator == '-':
        result = num1 - num2
    elif operator == '*':
        result = num1 * num2
    elif operator == '/':
        if num2 == 0:
            result = "Error! Division by zero."
        else:
            result = num1 / num2
    else:
        result = "Invalid operator"

    print("Result:", result)

calculator()